/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stasmlib_StasmController */

#ifndef _Included_stasmlib_StasmController
#define _Included_stasmlib_StasmController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stasmlib_StasmController
 * Method:    getImageFeaturePoints
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_stasmlib_StasmController_getImageFeaturePoints
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
